- Client/src/main/java/org/xdi/oxauth/client/RegisterClient.java
- Client/src/main/java/org/xdi/oxauth/client/RegisterRequest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/RegistrationRestWebServiceHttpTest.java
- Client/src/test/resources/testng.properties
- Model/src/main/java/org/xdi/oxauth/model/register/RegisterRequestParam.java
- RP/src/main/java/org/xdi/oxauth/action/OpenIdConnectDiscoveryAction.java
- RP/src/main/java/org/xdi/oxauth/action/RegistrationAction.java
- RP/src/main/webapp/home.xhtml
- Server/src/main/java/org/xdi/oxauth/model/registration/Client.java
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
Reverts GluuFederation/oxAuth#148
> Revert "Registration metadata"

- Client/src/main/java/org/xdi/oxauth/client/RegisterClient.java
- Client/src/main/java/org/xdi/oxauth/client/RegisterRequest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/RegistrationRestWebServiceHttpTest.java
- Client/src/test/resources/testng.properties
- Model/src/main/java/org/xdi/oxauth/model/register/RegisterRequestParam.java
- RP/src/main/java/org/xdi/oxauth/action/OpenIdConnectDiscoveryAction.java
- RP/src/main/java/org/xdi/oxauth/action/RegistrationAction.java
- RP/src/main/webapp/home.xhtml
- Server/src/main/java/org/xdi/oxauth/model/registration/Client.java
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
Reverts GluuFederation/oxAuth#150
> Revert "Revert "Registration metadata""

- Client/src/main/java/org/xdi/oxauth/client/model/authorize/JwtAuthorizationRequest.java
- Client/src/test/java/org/xdi/oxauth/interop/ProvidingIdTokenWithMaxAgeRestriction.java
- Client/src/test/java/org/xdi/oxauth/interop/RejectsSecondUseOfAccessCode.java
- Client/src/test/java/org/xdi/oxauth/interop/SecondUseOfAccessCodeRevokesPreviouslyIssuedAccessToken.java
- Client/src/test/java/org/xdi/oxauth/interop/SupportPromptValueLogin.java
- Client/src/test/java/org/xdi/oxauth/interop/SupportPromptValueNone.java
- Model/src/main/java/org/xdi/oxauth/model/jws/ECDSASigner.java
- Model/src/main/java/org/xdi/oxauth/model/jws/HMACSigner.java
- Model/src/main/java/org/xdi/oxauth/model/util/JwtUtil.java
- RP/src/main/java/org/xdi/oxauth/action/AuthorizationAction.java
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/model/common/AbstractToken.java
- Server/src/main/java/org/xdi/oxauth/model/common/AuthorizationGrantList.java
- Server/src/main/java/org/xdi/oxauth/model/common/AuthorizationGrantListLdap.java
- Server/src/main/java/org/xdi/oxauth/model/token/ClientAssertion.java
- Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java
- Server/src/main/java/org/xdi/oxauth/model/token/JwtSigner.java
- Server/src/main/java/org/xdi/oxauth/service/external/ExternalAuthenticationService.java
- Server/src/main/java/org/xdi/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/util/RedirectUtil.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - “ Dead stores should be removed ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1854
Please let me know if you have any questions.
Ayman Abdelghany.
> Dead stores should be removed

- Client/src/main/java/org/xdi/oxauth/client/JwkClient.java
- Client/src/main/java/org/xdi/oxauth/client/JwkResponse.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/JwkRestWebServiceHttpTest.java
- Model/src/main/java/org/xdi/oxauth/model/crypto/Key.java
- Model/src/main/java/org/xdi/oxauth/model/crypto/signature/ECDSAPrivateKey.java
- Model/src/main/java/org/xdi/oxauth/model/crypto/signature/ECDSAPublicKey.java
- Model/src/main/java/org/xdi/oxauth/model/crypto/signature/RSAKeyFactory.java
- Model/src/main/java/org/xdi/oxauth/model/crypto/signature/RSAPrivateKey.java
- Model/src/main/java/org/xdi/oxauth/model/crypto/signature/RSAPublicKey.java
- Model/src/main/java/org/xdi/oxauth/model/jwk/JSONWebKey.java
- Model/src/main/java/org/xdi/oxauth/model/jwk/JSONWebKeySet.java
- Model/src/main/java/org/xdi/oxauth/model/jwk/JWKParameter.java
- Model/src/main/java/org/xdi/oxauth/model/jwk/PrivateKey.java
- Model/src/main/java/org/xdi/oxauth/model/jwk/PublicKey.java
- Model/src/main/java/org/xdi/oxauth/model/util/JwtUtil.java
- Server/conf/oxauth-web-keys.json
- Server/src/main/java/org/xdi/oxauth/jwk/ws/rs/JwkRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/model/authorize/JwtAuthorizationRequest.java
- Server/src/main/java/org/xdi/oxauth/model/token/JwtSigner.java
- Server/src/main/java/org/xdi/oxauth/service/KeyGeneratorTimer.java
- Server/src/main/java/org/xdi/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/util/KeyGenerator.java
- Server/src/test/java/org/xdi/oxauth/comp/FederationSigningTest.java
Update test jwks data to conform latest code #93
> Update test jwks data

- RP/src/main/java/org/xdi/oxauth/action/EndSessionAction.java
- RP/src/main/webapp/home.xhtml
- RP/src/main/webapp/rpiframe.xhtml
- Server/src/main/java/org/xdi/oxauth/service/SessionStateService.java
- Server/src/main/java/org/xdi/oxauth/service/uma/RPTManager.java
- Server/src/main/webapp/WEB-INF/web.xml
- Server/src/main/webapp/opiframe.xhtml
Erase OPBS cookie on logout #155
> Erase opbs cookie on logout

- Client/src/test/java/org/xdi/oxauth/ws/rs/ClientAuthenticationFilterHttpTest.java
- Client/src/test/resources/testng.xml
- Server/src/main/java/org/xdi/oxauth/auth/AuthenticationFilter.java
- Server/src/main/java/org/xdi/oxauth/service/BaseAuthFilterService.java
- Server/src/main/java/org/xdi/oxauth/service/ClientFilterService.java
- Server/src/main/java/org/xdi/oxauth/service/ClientService.java
- Server/src/test/java/org/xdi/oxauth/ws/rs/ClientAuthenticationFilterEmbeddedTest.java
Fix ClientAuthenticationFilterEmbeddedTest #94
> Fix Client Authentication Filter

- Server/pom.xml
- Server/src/main/webapp/WEB-INF/web.xml
Support CORS specification to allow clients that are subjects for same origin policy to access vital pages at OP #175
> Support CORS #175

- Client/src/test/java/org/xdi/oxauth/BaseTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizationCodeFlowHttpTest.java
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/LoginAction.java
- Server/src/main/webapp/login.page.xml
- Server/src/main/webapp/login.xhtml
Pre-populate login form with login_hint #120
> Login hint

- Client/src/test/java/org/xdi/oxauth/ws/rs/RegistrationRestWebServiceHttpTest.java
- Server/conf/oxauth-config.json
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
"Update/Add client" page allows to set id_token's signing algorithm to none, resulting in unsigned id_token
> oxTrust #271

- Server/src/main/java/org/xdi/oxauth/model/ldap/PairwiseIdentifier.java
- Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java
- Server/src/main/java/org/xdi/oxauth/service/PairwiseIdentifierService.java
- Server/src/main/java/org/xdi/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
oxAuth #186
Pairwise ID: Algorithm should use sector identifier not URI
> #186 Pairwise ID: Algorithm should use sector identifier not URI

- Server/src/main/java/org/xdi/oxauth/model/ldap/TokenLdap.java
- Server/src/main/java/org/xdi/oxauth/token/ws/rs/TokenRestWebServiceImpl.java
Token Endpoint, Grant Type = REFRESH_TOKEN
The authorization server MAY issue a new refresh token, in which case the client MUST discard the old refresh token and replace it with the new refresh token.
> oxAuth #304

- Model/src/main/java/org/xdi/oxauth/model/configuration/Configuration.java
- Server/conf/oxauth-config.json
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/service/AuthenticationService.java
Disable subject-type claim for dynamic client reg / update client
> oxAuth #294

- Server/src/main/java/org/xdi/oxauth/util/KeyGenerator.java
- pom.xml
Update KeyGenerator to allow generate keys for oxEleven
> oxAuth #341

- Model/src/main/java/org/xdi/oxauth/model/configuration/Configuration.java
- Server/conf/oxauth-config.json
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/model/common/AuthorizationGrant.java
- Server/src/main/java/org/xdi/oxauth/model/common/IAuthorizationGrant.java
- Server/src/main/java/org/xdi/oxauth/model/common/UnmodifiableAuthorizationGrant.java
- Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java
- Server/src/main/java/org/xdi/oxauth/token/ws/rs/TokenRestWebServiceImpl.java
id_token should not contain user claims unless response_type=id_token
> oxAuth #340

- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
#188: Added the possibility to update scope via update client request
> Issue #188

- Server/src/main/java/org/xdi/oxauth/ws/rs/fido/u2f/U2fRegistrationWS.java
#335: Added the possibility to register another FIDO device, if current_authentication_level >= u2f_authentication_level.
@yurem how do you think, whether these changes are sufficient?
> #335: Added the possibility to register another FIDO device

- Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java
#244: These changes are tightly coupled with changes in oxCore (https://github.com/GluuFederation/oxCore/pull/6)
> #244 : Updated ID Token data structure

- Server/src/main/java/org/xdi/oxauth/gluu/ws/rs/GluuConfigurationWS.java
- Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/service/AppInitializer.java
- Server/src/main/java/org/xdi/oxauth/service/AuthenticationFilterService.java
- Server/src/main/java/org/xdi/oxauth/service/CleanerTimer.java
- Server/src/main/java/org/xdi/oxauth/service/ClientFilterService.java
- Server/src/main/java/org/xdi/oxauth/service/KeyGeneratorTimer.java
- Server/src/main/java/org/xdi/oxauth/service/MetricService.java
- Server/src/main/java/org/xdi/oxauth/service/PairwiseIdentifierService.java
- Server/src/main/java/org/xdi/oxauth/service/custom/CustomScriptManagerMigrator.java
- Server/src/main/java/org/xdi/oxauth/service/uma/ScopeService.java
- Server/src/main/java/org/xdi/oxauth/service/uma/UmaValidationService.java
- Server/src/main/java/org/xdi/oxauth/service/uma/resourceserver/PermissionService.java
- Server/src/main/java/org/xdi/oxauth/servlet/SectorIdentifier.java
- Server/src/main/java/org/xdi/oxauth/servlet/WebFinger.java
- Server/src/main/java/org/xdi/oxauth/uma/ws/rs/CreateRptWS.java
- Server/src/main/java/org/xdi/oxauth/uma/ws/rs/ResourceSetRegistrationWS.java
- Server/src/main/java/org/xdi/oxauth/uma/ws/rs/UmaConfigurationWS.java
- Server/src/main/java/org/xdi/oxauth/ws/rs/fido/u2f/U2fConfigurationWS.java
> - injected components

- Server/src/main/java/org/xdi/oxauth/auth/Authenticator.java
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java
- Server/src/main/java/org/xdi/oxauth/service/AuthenticationService.java
- Server/src/main/java/org/xdi/oxauth/service/FixedClientUidSelector.java
- Server/src/main/java/org/xdi/oxauth/service/SessionStateService.java
> - injected FacesContext and ExternalContext

- Server/src/main/java/org/xdi/oxauth/gluu/ws/rs/GluuConfigurationWS.java
- Server/src/main/java/org/xdi/oxauth/idgen/ws/rs/InumGenerator.java
- Server/src/main/java/org/xdi/oxauth/jwk/ws/rs/JwkRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/service/ApplianceService.java
- Server/src/main/java/org/xdi/oxauth/service/AttributeService.java
- Server/src/main/java/org/xdi/oxauth/service/ClientService.java
- Server/src/main/java/org/xdi/oxauth/service/GrantService.java
- Server/src/main/java/org/xdi/oxauth/service/ScopeService.java
- Server/src/main/java/org/xdi/oxauth/service/SectorIdentifierService.java
- Server/src/main/java/org/xdi/oxauth/service/SessionStateService.java
- Server/src/main/java/org/xdi/oxauth/service/UserService.java
- Server/src/main/java/org/xdi/oxauth/service/custom/CustomScriptService.java
- Server/src/main/java/org/xdi/oxauth/service/fido/u2f/AuthenticationService.java
- Server/src/main/java/org/xdi/oxauth/service/fido/u2f/DeviceRegistrationService.java
- Server/src/main/java/org/xdi/oxauth/service/fido/u2f/RegistrationService.java
- Server/src/main/java/org/xdi/oxauth/service/fido/u2f/RequestService.java
- Server/src/main/java/org/xdi/oxauth/service/uma/RPTManager.java
- Server/src/main/java/org/xdi/oxauth/service/uma/ResourceSetPermissionManager.java
- Server/src/main/java/org/xdi/oxauth/service/uma/ResourceSetService.java
- Server/src/main/java/org/xdi/oxauth/service/uma/resourceserver/PermissionService.java
> - injected configuration

- Server/src/main/java/org/xdi/oxauth/idgen/ws/rs/InumGenerator.java
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/service/ApplianceService.java
- Server/src/main/java/org/xdi/oxauth/service/AttributeService.java
- Server/src/main/java/org/xdi/oxauth/service/ClientService.java
- Server/src/main/java/org/xdi/oxauth/service/GrantService.java
- Server/src/main/java/org/xdi/oxauth/service/ScopeService.java
- Server/src/main/java/org/xdi/oxauth/service/SectorIdentifierService.java
- Server/src/main/java/org/xdi/oxauth/service/SessionStateService.java
- Server/src/main/java/org/xdi/oxauth/service/UserService.java
- Server/src/main/java/org/xdi/oxauth/service/custom/CustomScriptService.java
- Server/src/main/java/org/xdi/oxauth/service/fido/u2f/AuthenticationService.java
- Server/src/main/java/org/xdi/oxauth/service/fido/u2f/DeviceRegistrationService.java
- Server/src/main/java/org/xdi/oxauth/service/fido/u2f/RegistrationService.java
- Server/src/main/java/org/xdi/oxauth/service/fido/u2f/RequestService.java
- Server/src/main/java/org/xdi/oxauth/service/uma/ResourceSetService.java
- Server/src/main/java/org/xdi/oxauth/service/uma/resourceserver/PermissionService.java
> - injected StaticConf instead of ConfigurationFactory

- Server/src/main/java/org/xdi/oxauth/service/ClientService.java
> Enabled temporary disabled clientCache

- Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/xdi/oxauth/service/AuthenticationService.java
- Server/src/main/java/org/xdi/oxauth/service/ClientService.java
Issue #410:
- added new configuration attributes
> - added new configuration attributes

- Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java
- Model/src/main/java/org/xdi/oxauth/model/configuration/CorsConfigurationFilter.java
- Server/conf/oxauth-config.json
- Server/src/main/java/org/xdi/oxauth/filter/CorsFilter.java
- Server/src/main/java/org/xdi/oxauth/filter/CorsFilterConfig.java
- Server/src/main/webapp/WEB-INF/web.xml
oxAuth #458
Improve CORS configuration
> Improve CORS configuration

- Server/src/main/resources/messages.properties
- Server/src/main/resources/messages_bg.properties
- Server/src/main/resources/messages_de.properties
- Server/src/main/resources/messages_en.properties
- Server/src/main/resources/messages_es.properties
- Server/src/main/resources/messages_fr.properties
- Server/src/main/resources/messages_it.properties
- Server/src/main/resources/messages_ru.properties
- Server/src/main/resources/messages_tr.properties
Related with [this comment](https://github.com/GluuFederation/oxAuth/issues/506#issuecomment-295761695)
> Removed all keys of deprecated authentication methods in all resource bundles

- Client/src/test/java/org/xdi/oxauth/ws/rs/UserInfoRestWebServiceHttpTest.java
- Server/src/main/java/org/xdi/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
Add iss and aud to Userinfo Response
> oxAuth #511

- Server/src/main/java/org/xdi/oxauth/auth/Authenticator.java
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/LogoutAction.java
- Server/src/main/java/org/xdi/oxauth/i18n/LanguageBean.java
- Server/src/main/webapp/WEB-INF/faces-config.xml
- Server/src/main/webapp/WEB-INF/incl/layout/login-template.xhtml
- Server/src/main/webapp/WEB-INF/incl/layout/template.xhtml
- updated LanguageBean so that it can store locales in cookie
- removed locale selector from .xhtml files
Related with issue #502 .
> Localization in 3.1.x

- Client/src/test/java/org/xdi/oxauth/ws/rs/ClientCredentialsGrantHttpTest.java
- Server/src/main/java/org/xdi/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
NPE in UserInfoRestWebServiceImpl
> oxAuth #518

- Server/conf/oxauth-config.json
Security error thrown using implicit flow when request the userinfo endpoint
> oxAuth #529

- Client/src/test/java/org/xdi/oxauth/ws/rs/ApplicationTypeRestrictionHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizationCodeFlowHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/TokenEncryptionHttpTest.java
- Model/src/main/java/org/xdi/oxauth/model/jwt/JwtClaimName.java
- README
- Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java
Validation URL incorrect in access token
> oxAuth #547

- Model/src/main/java/org/xdi/oxauth/model/common/GrantType.java
Add UMA token grant type oxTrust#545
> Add UMA_TICKET grant type

- Server/pom.xml
Related with [#578](https://github.com/GluuFederation/oxTrust/issues/578#event-1113077588).
> - added new profile for native2ascii

- Server/src/main/java/org/xdi/oxauth/filter/CorsFilter.java
CORS filter doesn't seem to process pre-flight requests in CE 3.1.x
> oxAuth #542 CORS_Filter_CE-3.1.x

- Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java
- Server/conf/oxauth-config.json
- Server/src/main/java/org/xdi/oxauth/auth/Authenticator.java
- Server/src/main/java/org/xdi/oxauth/service/AuthenticationService.java
> oxAuth #577

- Model/src/main/java/org/xdi/oxauth/model/session/EndSessionErrorResponseType.java
- Server/conf/oxauth-errors.json
- Server/src/main/java/org/xdi/oxauth/model/session/EndSessionParamsValidator.java
- Server/src/main/java/org/xdi/oxauth/service/RedirectionUriService.java
- Server/src/main/java/org/xdi/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
> Added more detailed log messages for /end_session endpoint controller

- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java
Use default locale from face-config.xml instead of use english by default
> Use default locale from face-config.xml

- Server/src/main/java/org/xdi/oxauth/model/common/AbstractAuthorizationGrant.java
- Server/src/main/java/org/xdi/oxauth/model/registration/Client.java
> - added client-specific refresh token expiration

- Server/src/main/java/org/xdi/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
> - added redirect to RP on logout when id_token is expired

- Client/src/test/java/org/xdi/oxauth/ws/rs/TokenRestWebServiceHttpTest.java
- Server/src/main/java/org/xdi/oxauth/service/AuthenticationService.java
Error 500 on login with grant_type = password and bad password
> oxAuth #604

- Server/src/main/java/org/xdi/oxauth/model/fido/u2f/DeviceRegistration.java
Related with [this issue](https://github.com/GluuFederation/oxAuth/issues/228).
> - added nickname field to U2F device registration entry

- Server/src/main/resources/messages_en.properties
Added BeanValidator.MESSAGE key.
> oxTrust#652

- Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java
- Server/conf/oxauth-config.json
oxAuth#526 Added field enableClientGrantUpdate with getter setter methods
> Oxauth#526

- Server/src/main/webapp/WEB-INF/incl/layout/authorize-template.xhtml
- Server/src/main/webapp/authorize.xhtml
- Server/src/main/webapp/stylesheet/authorize.css
new design changes for Authorize page.
> Authorize page design

- Server/src/main/java/org/xdi/oxauth/exception/GlobalExceptionHandler.java
- Server/src/main/java/org/xdi/oxauth/exception/GlobalExceptionHandlerFactory.java
- Server/src/main/java/org/xdi/oxauth/exception/UncaughtException.java
- Server/src/main/webapp/WEB-INF/faces-config.xml
> - added global exception handlers for resteasy and jsf

- Model/src/main/java/org/xdi/oxauth/model/authorize/AuthorizeErrorResponseType.java
- Model/src/main/java/org/xdi/oxauth/model/token/TokenErrorResponseType.java
- Model/src/main/java/org/xdi/oxauth/model/uma/UmaErrorResponseType.java
- Server/conf/oxauth-errors.json
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/model/registration/Client.java
- Server/src/main/java/org/xdi/oxauth/token/ws/rs/TokenRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/uma/service/UmaTokenService.java
> - added disabled property in client model

- Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/model/common/AuthorizationGrant.java
- Server/src/main/java/org/xdi/oxauth/service/GrantService.java
> - added persistAuthorizationFlowInLdap to AppConfiguration

- Server/integrations/idp/IdpMultiAuthnExternalAuthenticator.py
- Server/integrations/passport/PassportExternalAuthenticator.py
- Server/src/main/webapp/auth/passport/passportpostlogin.xhtml
Add New IDP authentication script for EvolveIP Project
> IDP authentication script

- Client/src/main/java/org/xdi/oxauth/client/RegisterClient.java
- Client/src/main/java/org/xdi/oxauth/client/RegisterRequest.java
- Client/src/test/java/org/xdi/oxauth/interop/IncludesCHashInIdTokenWhenCodeFlowUsed.java
- Client/src/test/java/org/xdi/oxauth/interop/SupportRegistrationRead.java
- Client/src/test/java/org/xdi/oxauth/load/benchmark/BenchmarkRequestAccessToken.java
- Client/src/test/java/org/xdi/oxauth/load/benchmark/BenchmarkRequestAuthorization.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/ApplicationTypeRestrictionHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizationCodeFlowHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizeRestWebServiceHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizeSessionIdRestWebServiceHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/ClientCredentialsGrantHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/ClientWhiteListBlackListRedirectUris.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/GrantTypesRestrictionHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/MultiStepAuthorizationCodeFlowHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/RegistrationRestWebServiceHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/ResponseTypesRestrictionHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/TokenEndpointAuthMethodRestrictionHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/UILocales.java
- Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java
- Model/src/main/java/org/xdi/oxauth/model/register/RegisterRequestParam.java
- RP/src/main/webapp/home.xhtml
- Server/conf/oxauth-config.json
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
- Server/src/test/java/org/xdi/oxauth/ws/rs/ApplicationTypeRestrictionEmbeddedTest.java
- Server/src/test/java/org/xdi/oxauth/ws/rs/RegistrationRestWebServiceEmbeddedTest.java
- Server/src/test/java/org/xdi/oxauth/ws/rs/RequestObjectSigningAlgRestrictionEmbeddedTest.java
- Server/src/test/java/org/xdi/oxauth/ws/rs/ResponseTypesRestrictionEmbeddedTest.java
- Server/src/test/java/org/xdi/oxauth/ws/rs/TokenEndpointAuthMethodRestrictionEmbeddedTest.java
Invalid "scopes" field in Dynamic Client Registration request and response
> Invalid scopes field in Dynamic Client Registration request and response

- Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java
Create new JWK for use=enc for Client and Server tests
> oxAuth #699

- Client/src/test/java/org/xdi/oxauth/ws/rs/RegistrationRestWebServiceHttpTest.java
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
"subject_type" metadata element is rejected during OIDC Dynamic Registration client update flow
> oxAuth #707

- Server/integrations/passport/PassportExternalAuthenticator.py
Solved user add problem in passport-saml
> Solved user add problem in passport-saml

- Server/src/main/webapp/login.xhtml
Username remember me feature in login page
> oxAuth #728

- Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizationCodeFlowHttpTest.java
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java
Fix the list of scopes in the authorization page #739
> oxAuth #739

- Server/src/main/webapp/auth/otp/enroll.xhtml
- Server/src/main/webapp/auth/otp/otplogin.xhtml
I hope this time the commit message is correct.
> Ox auth/issues/807

- Client/src/main/java/org/xdi/oxauth/client/RegisterClient.java
- Client/src/main/java/org/xdi/oxauth/client/RegisterRequest.java
- Client/src/test/java/org/xdi/oxauth/BaseTest.java
- Client/src/test/java/org/xdi/oxauth/interop/ProvidingIndividuallyRequestedEssentialAndVoluntaryClaims.java
- Client/src/test/java/org/xdi/oxauth/interop/ProvidingIndividuallyRequestedEssentialClaims.java
- Client/src/test/java/org/xdi/oxauth/interop/ProvidingIndividuallyRequestedVoluntaryClaims.java
- Client/src/test/java/org/xdi/oxauth/interop/SupportClaimsRequestSpecifyingSubValue.java
- Client/src/test/java/org/xdi/oxauth/interop/SupportsCombiningClaimsRequestedWithScopeAndRequestObject.java
- Client/src/test/java/org/xdi/oxauth/interop/SupportsReturningDifferentClaimsInIdTokenAndUserInfoEndpoint.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/IndividualClaimsRequestsTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/OpenIDRequestObjectHttpTest.java
- Client/src/test/java/org/xdi/oxauth/ws/rs/UserInfoRestWebServiceHttpTest.java
- Client/src/test/resources/testng.xml
- Model/src/main/java/org/xdi/oxauth/model/register/RegisterRequestParam.java
- Server/conf/oxauth-config.json
- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java
- Server/src/main/java/org/xdi/oxauth/model/registration/Client.java
- Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java
- Server/src/main/java/org/xdi/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/service/AttributeService.java
- Server/src/main/java/org/xdi/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
- Server/src/main/resources/oxauth.properties
- Server/src/main/resources/oxauth_en.properties
- Server/src/main/resources/oxauth_es.properties
- Server/src/main/resources/oxauth_fr.properties
- Server/src/main/resources/oxauth_ru.properties
- Server/src/main/webapp/WEB-INF/incl/layout/authorize-extended-template.xhtml
- Server/src/main/webapp/authorize.xhtml
Restrict requesting claims individually
> oxAuth #812

- Server/src/main/webapp/auth/thumbsignin/README.md
- Server/src/main/webapp/auth/thumbsignin/expired.xhtml
- Server/src/main/webapp/auth/thumbsignin/js/authenticate-bundle.js
- Server/src/main/webapp/auth/thumbsignin/js/thumbsign_widget.js
- Server/src/main/webapp/auth/thumbsignin/js/thumbsignin_widget.css
- Server/src/main/webapp/auth/thumbsignin/tsLogin.xhtml
- Server/src/main/webapp/auth/thumbsignin/tsRegister.xhtml
- Server/src/main/webapp/auth/thumbsignin/tsRegistrationSuccess.xhtml
> Added ThumbSignIn XHTML Pages

- Client/pom.xml
- Client/src/main/java/org/xdi/oxauth/client/OpenIdConfigurationClient.java
- pom.xml
application/json added to OpenIdConfiguration request
oxauth-model test-jar dependency
> application/json added to OpenIdConfiguration request

- Server/integrations/azuread/AzureADAuthenticationForGluu.py
- Server/integrations/azuread/README.md
Added custom Jython script which can be used to achieve Azure AD based user authentication for Gluu.
> Add Azure AD authentication support for Gluu

- Server/src/main/java/org/gluu/oxauth/service/SessionIdService.java
- Server/src/main/java/org/gluu/oxauth/service/external/ExternalAuthenticationService.java
Changes in reference to
Gluu Server SAML NameID enhacement #1651
Map AuthnContextClassRef --> acr in OpenID Connect #15
> #1651, #15

- Model/src/main/java/org/gluu/oxauth/model/uma/persistence/UmaPermission.java
- Model/src/main/java/org/gluu/oxauth/model/uma/persistence/UmaResource.java
https://github.com/GluuFederation/oxAuth/issues/1161
> Fix UmaResource deserialization in redis case.

- Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/xdi/oxauth/service/SessionIdService.java
- Server/src/main/java/org/xdi/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
Hi,
I've spent a lot of time researching issues related to oidc session change detection as it was not properly working with Gluu 3.1.6 and later.
I've discussed my research and provided a complete bug report in the following repo https://github.com/livetocode/gluu-oxauth-bug-report-01, which also includes sample projects for reproducing the issues.
I don't know if this PR is the final solution to the reported issues but at least I managed to get it working with very few changes.
Hope this helps,
Morgan Martinet
> fix oidc session change detection

- Server/integrations/forgot_password/forgot_password.py
- Server/src/main/webapp/auth/forgot_password/forgot.xhtml
- Server/src/main/webapp/auth/forgot_password/newpassword.xhtml
- Server/src/main/webapp/auth/forgot_password/resettoken.xhtml
Forgot password auth interception script asked by mike
> Forgot password intercept

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/gluu/oxauth/service/logger/LoggerService.java
Added json property to change logs layout between json or text.
> JsonLayout for logs

- Server/src/main/java/org/gluu/oxauth/model/registration/RegisterParamsValidator.java
- Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
This PR is related to this issue: https://github.com/GluuFederation/oxAuth/issues/1062
> Validate supported algorithms in the client registration endpoint

- Client/src/test/java/org/gluu/oxauth/ciba/BackchannelAuthenticationPingMode.java
- Client/src/test/java/org/gluu/oxauth/ciba/BackchannelAuthenticationPollMode.java
- Client/src/test/resources/testng.xml
> oxAuth #750

- Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java
- Server/src/main/java/org/gluu/oxauth/service/RequestParameterService.java
Issue: #1171 
Jenkins execution passed: https://ox.gluu.org/jenkins/job/oxAuth_master_LDAP/858/console
> Support custom parameters in request object

- RP/src/main/java/org/gluu/oxauth/action/RegistrationAction.java
A small improvement in order to have the client notification endpoint already put.
> Added client notification url by default for oxAuth-RP.

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
> Added flag to toggle default code flow behaviour

- Server/src/main/java/org/gluu/oxauth/servlet/OpenIdConfiguration.java
- persistence-model/src/main/java/org/oxauth/persistence/model/Scope.java
Related to this issue: https://github.com/GluuFederation/oxAuth/issues/1370
> New scope attribute to publish or not in discovery endpoint

- Server/conf/oxauth-config.json
Last success build: https://ox.gluu.org/jenkins/job/oxAuth_master_LDAP/977
> Added clientRegDefaultToCodeFlowWithRefresh flag in config file.

- Server/src/main/java/org/gluu/oxauth/servlet/OpenIdConfiguration.java
- persistence-model/src/main/java/org/oxauth/persistence/model/Scope.java
- persistence-model/src/main/java/org/oxauth/persistence/model/ScopeAttributes.java
Success Jenkins execution: https://ox.gluu.org/jenkins/job/oxAuth_master_LDAP/991
> Moved notShowInDiscovery Scope attribute

- Client/pom.xml
- Client/src/test/java/org/gluu/oxauth/BaseTest.java
- Client/src/test/java/org/gluu/oxauth/page/AbstractPage.java
- Client/src/test/java/org/gluu/oxauth/page/SelectPage.java
- pom.xml
After several tests and intents to fix the security issue, I had many solutions, however most of them were very slow, however at the end I decided to change the `htmlunit-driver` to `selenium-htmlunit-driver`, the time is almost the same than we still have in `master` version.
Success Jenkins execution: https://ox.gluu.org/jenkins/job/oxAuth_master_LDAP/1020
Issue: https://github.com/GluuFederation/oxAuth/issues/1379
> Updated Html Unit Driver libraries

- Server/integrations/saml-passport/SamlPassportAuthenticator.py
> fixed isInboundJwt exception

- RP/src/main/java/org/gluu/oxauth/action/DeviceAuthzAction.java
- RP/src/main/java/org/gluu/oxauth/action/OpenIdConnectDiscoveryAction.java
- RP/src/main/java/org/gluu/oxauth/action/RegistrationAction.java
- RP/src/main/webapp/device_authorization.xhtml
- RP/src/main/webapp/home.xhtml
> Device Authorization & oxAuth-RP

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java
- Server/src/main/java/org/gluu/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
Issue: https://github.com/GluuFederation/oxAuth/issues/1429
> Oidcc basic certification

- Server/integrations/saml-passport/SamlPassportAuthenticator.py
updating 4.2.1 branch as requested
> Latest version

- Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
Based on the certification process, state param should be part of the redirect url, due logout certification will be delayed a little, I'm creating this PR.
#1429
> Added state query param in post_logout_redirect_uri

- Server/src/main/java/org/gluu/oxauth/auth/AuthenticationFilter.java
- Server/src/main/java/org/gluu/oxauth/model/token/HttpAuthTokenType.java
- Server/src/main/java/org/gluu/oxauth/service/token/TokenService.java
Patch to allow our gluu-spnego authentication module to work in 4.2.x
> Pull request from Djeumen Rolain

- Server/integrations/saml-passport/SamlPassportAuthenticator.py
> removed noise from passport-saml "logging"

- Server/integrations/passport/PassportExternalAuthenticator.py
> fix: update passport social script to handle provider config state problem

- Server/integrations/passport/PassportExternalAuthenticator.py
- Server/integrations/saml-passport/SamlPassportAuthenticator.py
close #1482  
@christian-hawk  Please review it, after merge, I'll make PR for `GluuFederation/community-edition-setup` and `JanssenProject/jans-auth-server` repos
> fix: update jwt date check function in passport scripts

- Server/integrations/privacyidea/README.md
- Server/integrations/privacyidea/pages/auth/privacyidea/privacyidea.xhtml
- Server/integrations/privacyidea/privacyidea.py
* Script, page for second step and installtion instructions
> privacyidea integration

- Server/integrations/basic.passwordchangewithvalidations/INSTALLATION.txt
- Server/integrations/basic.passwordchangewithvalidations/PasswordChangeWithValidations.py
- Server/integrations/basic.passwordchangewithvalidations/pwd/newpassword.xhtml
Added a new custom script for password change with validations
> added custom script password change

- Server/integrations/forgot_password/forgot_password.py
- Server/src/main/webapp/auth/forgot_password/forgot.xhtml
> fix(forgot_password): update script compatibility

- Server/integrations/new_acr_link/README.md
- Server/integrations/new_acr_link/new_acr_link.py
Instructions in `README.md` file.
I haven't pushed a `login.xhtml` as the urls are dinamyc according to custom `configurationAttributes`.
> feat(new-acr-link): create script to replace acr_values in authz url

- Client/src/main/java/org/gluu/oxauth/util/KeyGenerator.java
- Model/src/main/java/org/gluu/oxauth/model/crypto/AbstractCryptoProvider.java
- Model/src/main/java/org/gluu/oxauth/model/crypto/OxAuthCryptoProvider.java
- Model/src/main/java/org/gluu/oxauth/model/crypto/OxElevenCryptoProvider.java
- Server/src/main/java/org/gluu/oxauth/service/ServerCryptoProvider.java
- Server/src/test/java/org/gluu/oxauth/comp/CrossEncryptionTest.java
feat: added ability to specify key length for KeyGenerator
https://github.com/GluuFederation/oxAuth/issues/1587
> feat: added ability to specify key length for KeyGenerator

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/conf/oxauth-config.json
- Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
Issue: https://github.com/GluuFederation/oxAuth/issues/1561
> Fix: Added flag to toogle autofix for grant types and response types

- Server/src/main/webapp/login.xhtml
https://github.com/GluuFederation/oxAuth/issues/1556
> fix: login_hint not appearing

- Client/src/main/java/org/gluu/oxauth/client/ciba/fcm/FirebaseCloudMessagingResponse.java
- Client/src/main/java/org/gluu/oxauth/client/ciba/ping/PingCallbackResponse.java
- Client/src/main/java/org/gluu/oxauth/client/ciba/push/PushErrorResponse.java
- Client/src/main/java/org/gluu/oxauth/client/ciba/push/PushTokenDeliveryResponse.java
Related to PR: https://github.com/GluuFederation/oxAuth/pull/1637
Adding change to version 4.3.1.sp1.
> Fix: fixed resteasy response response construction

- common/src/main/java/org/gluu/oxauth/model/registration/Client.java
- persistence-model/src/main/java/org/oxauth/persistence/model/Scope.java
https://github.com/GluuFederation/oxAuth/issues/1651
> fix(master): removed duplicated dn field

- Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
https://github.com/GluuFederation/oxAuth/issues/1658
> fix(oxauth): added audit of client deletion event

- Server/src/main/webapp/login.xhtml
> fix: issue 1365 added required message

- Model/src/main/java/org/gluu/oxauth/model/uma/persistence/UmaPermission.java
- Model/src/main/java/org/gluu/oxauth/model/uma/persistence/UmaResource.java
- Model/src/main/java/org/gluu/oxauth/model/util/Util.java
- Server/src/main/java/org/gluu/oxauth/model/common/AbstractToken.java
Reported via support ticket. Fixing util to calculate difference in seconds between two dates.
> Fixed duration in seconds from date until now

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java
- Server/src/main/java/org/gluu/oxauth/service/RedirectUriResponse.java
- Server/src/main/java/org/gluu/oxauth/service/RedirectionUriService.java
- Server/src/test/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequestTest.java
feat(oxauth): added restriction for request_uri parameter (blacklist/allowed list) (4.4.1)
https://github.com/JanssenProject/jans/issues/1503
(cherry picked from commit c567baf9caf648d361b222c5beb742dfb64cc5ca)
> feat(oxauth): added restriction for request_uri parameter (blacklist/allowed list) (4.4.1)

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java
- Server/src/test/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequestTest.java
https://github.com/JanssenProject/jans/issues/1503
(cherry picked from commit bcbabc1c7f4de9badb1ee6ce50ee8d74cdf8894d)
> chore(oxauth): renamed requestUriBlackList -> requestUriBlockList (4.5)

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/gluu/oxauth/service/SpontaneousScopeService.java
- Server/src/main/java/org/gluu/oxauth/service/external/context/DynamicScopeExternalContext.java
- Server/src/main/java/org/gluu/oxauth/uma/service/UmaScopeService.java
feat(oxauth): added AS JSON config for allowSpontaneousScopes #1705
https://github.com/GluuFederation/oxAuth/issues/1705
doc: not docs
> feat(oxauth): Auth Server JSON config for allowSpontaneousScopes #1705

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
Fix SpontaneousScopeHttpTest.
https://github.com/GluuFederation/oxAuth/issues/1725
> test(oxauth): SpontaneousScopeHttpTest fails during build #1725

- Server/src/test/java/org/gluu/oxauth/ws/rs/TokenEndpointAuthMethodRestrictionEmbeddedTest.java
test(oxauth): tring to get embedded test work under spanner
> test(oxauth): tring to get embedded test work under spanner

- Model/src/main/java/org/gluu/oxauth/model/util/Util.java
- Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
fix(oxauth): npe fix
NPE introduced by previous PR, see https://github.com/GluuFederation/oxAuth/pull/1730
> fix(oxauth): npe fix

- Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
end session - if id_token is expired but signature is correct, we should make attempt to look up session by "sid" claim #1759
> feat(oxauth): end session - if id_token is expired but signature is correct, look up session by sid claim

- Server/src/main/java/org/gluu/oxauth/service/external/ExternalIntrospectionService.java
- Server/src/main/java/org/gluu/oxauth/service/external/ExternalUpdateTokenService.java
- Server/src/main/java/org/gluu/oxauth/service/external/context/ExternalScriptContext.java
feat(oxauth): add ability to return error out of introspection and update_token custom scripts #1760
> feat(oxauth): add ability to return error out of introspection and update_token custom scripts #1760

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/conf/oxauth-config.json
- Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
A new configuration `return200OnClientRegistration` has been added, by default this field is set to `true`
#1780
> Feature: Change response status 200 (Ok) by 201 (Created) for Client Registration

- Server/src/main/java/org/gluu/oxauth/model/token/IdTokenFactory.java
Added the `setClaimsFromRequestedClaims` method that adds the claims according to the request.
#1793
> Fix: Claims From Request

- Model/src/main/java/org/gluu/oxauth/model/crypto/AbstractCryptoProvider.java
Added a method to check if the `kid` is null
#1797
> Fix: Kid null in getPublicKey

- Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java
- Server/src/main/java/org/gluu/oxauth/util/RedirectUtil.java
Added responseMode in JwtAturhozationRequest
#1801
> Fix: Added responseMode in JwtAuthorizationRequest

- Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
> Fix: initiate_login_uri now response invalid_client_metadata

- Server/src/test/java/org/gluu/oxauth/service/RedirectionUriServiceTest.java
- Server/src/test/resources/testng.xml
test(oxauth): added RedirectionUriServiceTest #1805
> test(oxauth): added RedirectionUriServiceTest #1805

- pom.xml
https://github.com/GluuFederation/oxTrust/issues/2334
> fix(oxauth-server): updated the dependency versions oxtrust issue 2334

- Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
fix(oxauth): corrected post_logout_redirect_uri validation #1820
> fix(oxauth): corrected post_logout_redirect_uri validation #1820

- Model/src/main/java/org/gluu/oxauth/model/jwt/Jwt.java
- Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/gluu/oxauth/model/common/AbstractAuthorizationGrant.java
- Server/src/main/java/org/gluu/oxauth/model/common/AuthorizationGrant.java
- Server/src/main/java/org/gluu/oxauth/model/common/ExecutionContext.java
- Server/src/main/java/org/gluu/oxauth/model/common/IAuthorizationGrant.java
- Server/src/main/java/org/gluu/oxauth/model/common/UnmodifiableAuthorizationGrant.java
- Server/src/main/java/org/gluu/oxauth/model/token/IdTokenFactory.java
- Server/src/main/java/org/gluu/oxauth/service/external/ExternalUpdateTokenService.java
- Server/src/main/java/org/gluu/oxauth/service/external/context/ExternalUpdateTokenContext.java
- Server/src/main/java/org/gluu/oxauth/token/ws/rs/TokenRestWebServiceImpl.java
feat(oxauth): introduce new UpdateToken methods #1728
> feat(oxauth): introduce new UpdateToken methods #1728

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/gluu/oxauth/service/GrantService.java
- Server/src/main/java/org/gluu/oxauth/service/SessionIdService.java
feat(oxauth): make not found exception logging level configurable
https://github.com/GluuFederation/oxAuth/issues/1774
> feat(oxauth): make not found exception logging level configurable #1774

- Server/src/main/java/org/gluu/oxauth/auth/AuthenticationFilter.java
> fix: in 4.5 and in 4.3.1.sp1, server responding with 200 even when

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Server/src/main/java/org/gluu/oxauth/auth/AuthenticationFilter.java
https://github.com/GluuFederation/oxAuth/issues/1854
> fix: Authentication Filter should not process OPTIONS request method

- Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
- Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionUtils.java
fix(oxauth): state is not always returned on redirect from /end_session endpoint #1857 (master)
https://github.com/GluuFederation/oxAuth/issues/1857
> fix(oxauth): state is not always returned on redirect from /end_session endpoint #1857 (master)

- Server/src/main/java/org/gluu/oxauth/introspection/ws/rs/IntrospectionWebService.java
- Server/src/main/java/org/gluu/oxauth/model/common/AbstractAuthorizationGrant.java
- Server/src/main/java/org/gluu/oxauth/model/common/AuthorizationGrantList.java
fix(oxauth): cnf introspection response is null even when valid cert is send during MTLS #6343 #1868
https://github.com/GluuFederation/oxAuth/issues/1868
> fix(oxauth): cnf introspection response is null even when valid cert is send during MTLS #6343 #1868

- Server/integrations/duo-universal-prompt/DuoUniversalPromptExternalAuthenticator.py
> fix(oxauth): Indentation errors

- docs/oxAuthSwagger.yaml
> docs(oxauth): fix metadata for swagger

- stat-exporter/src/main/java/org/gluu/stat/exporter/StatExporter.java
Made stat-exporter work with jans-auth-server.
Closes #1859
https://github.com/GluuFederation/oxAuth/issues/1859
> fix(stat-exporter): stat exporter can't run against jans-auth-server

- Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java
fix(oxauth): backported id_token validation method from 4.5.3->4.2.3.sp2
https://github.com/GluuFederation/oxAuth/issues/1881
> fix(oxauth): backported id_token validation method from 4.5.3->4.2.3.sp2

- Server/integrations/super_gluu/SuperGluuExternalAuthenticator.py
> docs: add lifetime to Supergluu

- Model/src/main/java/org/gluu/oxauth/model/authorize/AuthorizeErrorResponseType.java
- Server/conf/oxauth-errors.json
- Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
- Server/src/test/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceValidatorTest.java
- docs/oxAuthSwagger.yaml
feat(oxauth): the requestUriParameterSupported and requestParameterSupported involved in request processing
https://github.com/GluuFederation/oxAuth/issues/1891
> feat(oxauth): the requestUriParameterSupported and requestParameterSupported involved in request processing

- Server/src/main/webapp/WEB-INF/incl/layout/login-extended-template.xhtml
> fix(oxauth-server): change js lib path

- Server/src/main/webapp/WEB-INF/incl/layout/login-extended-template.xhtml
> Ox auth issues 1896

- Model/src/main/java/org/gluu/oxauth/model/crypto/AbstractCryptoProvider.java
- Model/src/main/java/org/gluu/oxauth/model/crypto/OxElevenCryptoProvider.java
fix(oxauth): OxElevenCryptoProvider should pass all jwks, not just first key
https://github.com/GluuFederation/oxAuth/issues/1900
> fix(oxauth): OxElevenCryptoProvider should pass all jwks, not just first key

- Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java
- Model/src/main/java/org/gluu/oxauth/model/util/URLPatternList.java
- Model/src/test/java/org/gluu/oxauth/model/util/Tester.java
- Model/src/test/java/org/gluu/oxauth/model/util/URLPatternListTest.java
- Server/src/main/java/org/gluu/oxauth/model/registration/RegisterParamsValidator.java
- Server/src/main/java/org/gluu/oxauth/service/RedirectionUriService.java
feat(oxauth): support wildcard character in redirect_uri #1918
> feat(oxauth): support wildcard character in redirect_uri #1918

- common/src/main/java/org/gluu/oxauth/util/RedirectUri.java
- common/src/test/java/org/gluu/oxauth/util/RedirectUriTest.java
- common/src/test/resources/testng.xml
fix(oxauth): prevent rxss #1923
> fix(oxauth): prevent rxss #1923
