Server/src/main/java/org/xdi/oxauth/model/config/ConfigurationFactory.java
Multi-instance tomcat installations have a single CATALINA_HOME where the tomcat shared libraries are stored and can have one or more CATALINA_BASE directories which contains a local instance of tomcat with customized configs. The ubuntu packages, tomcat{6,7}-user, assist in creating such multi-instance installations by generating a new CATALINA_BASE directory with a copy of the essential configs. Ideally, a tomcat application will first look for its config files under CATALINA_BASE first, then CATALINA_HOME.
Right now oxauth only checks CATALINA_HOME for its configs. This patch should help oxauth to be deployed in cases where configs are stored in CATALINA_BASE instead of CATALINA_HOME.
=> Support the use of the catalina.base for multi-instance tomcat installations

Server/conf/oxauth-config.json
The website asset paths (cssLocation, imgLocation, and jsLocation) stored in the oxauth-config.json template all use a compile time variable config.oxauth.contextPath prefixed with a "/", forcing the assets to be relative to the current url. HOWEVER, config.oxauth.contextPath is NOT set as a relative URL in the relevant sample properties files (it defaults to https://localhost:8443), nor is it used this way in the other entries that use it (authorizationEndpoint, tokenEndpoint, userInfoEndpoint, etc). This commit changes the default profile to remove the "/" prefix from the assets paths.
=> Do not force the use of relative paths for css, images, or javascripts.

Server/src/main/java/org/xdi/oxauth/servlet/OpenIdConfiguration.java
#328: Removed uma_authorization and uma_protection scopes from openid discovery
=> Issue #328

Server/src/main/java/org/xdi/oxauth/servlet/OpenIdConfiguration.java
Issue #366. Removed double-array from auth_level_mapping
=> - removed double-array from auth_level_mapping

Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java, Server/conf/oxauth-config.json, Server/src/main/java/org/xdi/oxauth/service/SessionStateService.java
Support JSON Property for HTTPOnly
To enable it, set sessionStateHttpOnly: true in oxAuth config.
Note that SessionManagement will not work.
See http://openid.net/specs/openid-connect-session-1_0.html
Note that your browser should not allow a client-side script to access the session_state cookie. Unfortunately, since the attribute is relatively new, several browsers may neglect to handle the new attribute properly.
See https://www.owasp.org/index.php/HttpOnly
=> oxAuth #412

Server/integrations/basic.multi_auth_conf/BasicMultiAuthConfExternalAuthenticator.py
AppInitializer.instance() doesn't seem to be defined anymore and is throwing a null pointer exception in Jython.
Replacing with Component.getInstance() instead.
=> Fix null pointer on 3.0.0 (ticket #3743)

Server/src/main/java/org/xdi/oxauth/auth/AuthenticationFilter.java
#590: removed the need to pass client_secret to '/oxauth/restv1/token' endpoint if client authorization method is 'none'.
=> Issue 590.

Server/integrations/gplus/GooglePlusExternalAuthenticator.py
- When enrolling users through Google+/Google OAuth2, the user created
in Gluu's LDAP did not have the oxTrustEmail attribute
set. Consequentially, the email array of these users, when queried
through the SCIM REST API, was empty.
- This has now been remedied. The following email entry is added to
the SCIM JSON structure for a user created through G+:
```
"emails": [
{
"operation": null,
"value": "user@gmail.com",
"display": "user@gmail.com",
"primary": true,
"reference": null,
"type": "other"
}
],
```
- Roughly equivalent to
org.gluu.oxtrust.util.ServiceUtil#syncEmailReverse (which can't be
used becaues the models are different).
=> Users enrolled through Google+ now have SCIM emails array set

Client/src/test/java/org/xdi/oxauth/ws/rs/MultiStepAuthorizationCodeFlowHttpTest.java, Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java
=> Don't throw NPE when there is no legacyDynamicRegistrationScopeParam in

Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizeRestWebServiceHttpTest.java, Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java, Server/conf/oxauth-config.json, Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java
oxAuth #743
Add JSON property to enable admin to turn off authz for openid scope
If a client has only openid scope and pairwise id, person should not have to authorize.
=> oxAuth #743

Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizeRestWebServiceHttpTest.java, Client/src/test/java/org/xdi/oxauth/ws/rs/MultivaluedClaims.java, Server/conf/oxauth-config.json
oxAuth #743
Add JSON property to enable admin to turn off authz for openid scope
If a client has only openid scope and pairwise id, person should not have to authorize.
=> Version 3.1.3 enable admin to turn off authz for openid scope

Client/src/test/java/org/xdi/oxauth/ws/rs/SectorIdentifierUrlVerificationHttpTest.java, Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java, Server/conf/oxauth-config.json, Server/src/main/java/org/xdi/oxauth/service/PairwiseIdentifierService.java
Add a config value to allow to share the same sub between two Clients with the same sector identifier
https://github.com/GluuFederation/oxAuth/issues/1063
=> oxAuth #1063

Client/src/main/java/org/gluu/oxauth/client/uma/UmaClientFactory.java
#423 - Fix oxd after httpclient upgrade in oxauth 
https://github.com/GluuFederation/oxd/issues/423
This PR to fix following issue: ` In '/uma-rs-protect',  after deleting the first resource, the same `resource Id` is passed to oxauth, although correct `resource Id` from oxd in the loop.`
To fix this issue `UriBuilder#fromPath` should not be used as it uses `jersy` implementation of UriBuilder which is causing this issue. To correct this we should directly use `ResteasyUriBuilder` (Resteasy implementation of UriBuilder).
=> #423 - Fix oxd after httpclient upgrade in oxauth 

Server/integrations/saml-passport/SamlPassportAuthenticator.py
Related to #1306 
I was able to reproduce, and now the script blocks **none attacks** on the passport-saml side.
I changed `.getSigningAlgorithm` (was not working in my server) to `.getAlgorithm()` method (please see comments).
I also left the `customScript` arg  at `PersonAuthenticator` arg (need to remove to work on my version)
=> Issue #1306 mitigate replay modified jwt passport

Server/integrations/saml-passport/SamlPassportAuthenticator.py
This PR is related to issue  on gluu-passport: https://github.com/GluuFederation/gluu-passport/issues/95
and to gluu-passport PR: https://github.com/GluuFederation/gluu-passport/pull/97
For now, the inbound-saml script should receive and base64url encoded state.
Please do not merge PR during draft.
-  Here inbound-saml script also deals with the timer restart of external scripts.
=> Passport Issue 95 replace dot jwt auth z

Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java, Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java, Server/src/main/java/org/gluu/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
Two small changes:
1. Use seconds instead of milliseconds in User Info response.
2. Add flag to enable/disable hash validation for `request_uri` param.
Test plan: https://www.certification.openid.net/plan-detail.html?plan=DF5fIFd6lr2rM&public=true
Jenkins build: https://ox.gluu.org/jenkins/job/oxAuth_master_LDAP/1219/
Issue: https://github.com/GluuFederation/oxAuth/issues/1429
=> Oidcc basic certification

Client/pom.xml, pom.xml
After some tests I didn't find any issue using parallel feature, failed tests were related to disk space stuff, therefore I think we are ready to revert Selenium dependencies.
Last Jenkins build: https://ox.gluu.org/jenkins/job/oxAuth_master_LDAP/1401/
=> Reverted Selenium dependencies

common/src/main/java/org/gluu/oxauth/service/UserService.java
Need to be able to find multiple users based on an attribute, but getUsersBySample does not support multi-value so cannot use CB indexes properly.
=> Created a function to get multiple users

Client/src/main/java/org/gluu/oxauth/client/RegisterClient.java, Client/src/main/java/org/gluu/oxauth/client/RegisterRequest.java, Client/src/test/java/org/gluu/oxauth/ws/rs/EndSessionRestWebServiceHttpTest.java, Client/src/test/java/org/gluu/oxauth/ws/rs/GrantTypesRestrictionHttpTest.java, Client/src/test/java/org/gluu/oxauth/ws/rs/RegistrationRestWebServiceHttpTest.java, RP/src/main/java/org/gluu/oxauth/action/RegistrationAction.java, Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java, Server/src/test/java/org/gluu/oxauth/ws/rs/EndSessionRestWebServiceEmbeddedTest.java
#553 - Change `client_frontchannel_logout_uri` from `List` to `string`  type during client registration
https://github.com/GluuFederation/oxd/issues/553
=> #553 - Change `client_frontchannel_logout_uri` from `List` to `string`  type during client registration

Client/src/test/java/org/gluu/oxauth/ws/rs/RegistrationRestWebServiceHttpTest.java, Client/src/test/java/org/gluu/oxauth/ws/rs/RegistrationWithSoftwareStatement.java, Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java, Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java, common/src/main/java/org/gluu/oxauth/model/registration/Client.java
Issue#553 - Change `client_frontchannel_logout_uri` from `List` to `string` type during client registration
https://github.com/GluuFederation/oxd/issues/553
Changed `common/src/main/java/org/gluu/oxauth/model/registration/Client.frontChannelLogoutUri` from `String[]` to `Sting` to correct the test cases
=> Issue#553 - Change `client_frontchannel_logout_uri` from `List` to `string` type during client registration

Server/src/main/webapp/uma2/sample/claims_resolved.xhtml, Server/uma/sample/UmaClaimsGathering.py
If `pct` is passed by client in request and claims are found in `pct` it will redirect to `claims_resolved.xhtml` page showing message `All Claims Resolved from previous RPT authorization`. On click of proceed button it will go to the upstream application.
=> #1056 Modify the `claims-gathering` script so that it first tries to read claims from PCT before directing to the page to enter claims.

Client/src/main/java/org/gluu/oxauth/client/ciba/fcm/FirebaseCloudMessagingResponse.java, Client/src/main/java/org/gluu/oxauth/client/ciba/ping/PingCallbackResponse.java, Client/src/main/java/org/gluu/oxauth/client/ciba/push/PushErrorResponse.java, Client/src/main/java/org/gluu/oxauth/client/ciba/push/PushTokenDeliveryResponse.java
During RESTEasy lib update, an issue was introduced, client response classes were initialized incorrectly, enforcing response instance to be loaded twice, so it lead into this issue:
```
IllegalStateException is thrown with the following message RESTEASY003765: Response is closed.
```
=> Fix: fixed resteasy response init for CIBA classes

Server/src/main/java/org/gluu/oxauth/service/SessionIdService.java
Print message without stack trace.
https://github.com/GluuFederation/oxAuth/issues/1646
=> fix(oxauth): reduce noise in logs when session can't be found #1646

Model/src/main/java/org/gluu/oxauth/model/crypto/OxAuthCryptoProvider.java, Model/src/main/java/org/gluu/oxauth/model/util/CertUtils.java
fix(oxauth): corrected signature algorithm identification with java 11 and later (4.4)
https://github.com/GluuFederation/oxAuth/issues/1661
=> fix(oxauth): corrected signature algorithm identification with java 11 and later (4.4)

Server/src/main/java/org/gluu/oxauth/auth/MTLSService.java, Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java, Server/src/main/java/org/gluu/oxauth/model/token/ClientAssertion.java, Server/src/main/java/org/gluu/oxauth/model/token/JwrService.java, Server/src/main/java/org/gluu/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java, Server/src/main/java/org/gluu/oxauth/util/ServerUtil.java
fix(oxauth): use client's jwks if its present before fetching by jwks_uri
https://github.com/GluuFederation/oxAuth/issues/1674
=> fix(oxauth): use client's jwks if its present before fetching by jwks_uri

Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java, Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java, Server/src/main/java/org/gluu/oxauth/service/RedirectUriResponse.java, Server/src/main/java/org/gluu/oxauth/service/RedirectionUriService.java, Server/src/test/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequestTest.java
feat(oxauth): added restriction for request_uri parameter (blacklist/allowed list) (4.5)
https://github.com/JanssenProject/jans/issues/1503
=> feat(oxauth): added restriction for request_uri parameter (blacklist/allowed list) (4.5)

Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, Server/src/main/java/org/gluu/oxauth/token/ws/rs/TokenRestWebServiceImpl.java
From a support ticket, we found that we need to include dynamic scopes as part of idToken generation for CIBA grant type.
Issue: https://github.com/GluuFederation/oxAuth/issues/1701
=> Fix / include idtoken with dynamic scopes for ciba

Server/src/main/resources/oxauth_de.properties
Some translation in the file oxauth_de.properties is in Spanish or English. Changed it to German, otherwise the browser shows the wrong language, if default language is German. See also this [support question](https://support.gluu.org/identity-management/8955/login-site-shows-wrong-language/)
Please verify and merge on occasion
=> Fix german translation in oxauth_de.properties

Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java, Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceValidator.java, Server/src/test/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceValidatorTest.java, Server/src/test/resources/testng.xml
Issue: https://github.com/GluuFederation/oxAuth/issues/1714
Setting max_age parameter with 0 value in a authorization request doesn't allow user to log in at all. After postlogin call user is redirected back to login page.
In addition we can introduce `disableAuthnForMaxAgeZero` with default value `false`. If `true` - authn will be disabled.
```
max_age
OPTIONAL. Maximum Authentication Age. Specifies the allowable elapsed time in seconds since the last time the End-User was actively authenticated by the OP. If the elapsed time is greater than this value, the OP MUST attempt to actively re-authenticate the End-User. (The max_age request parameter corresponds to the OpenID 2.0 PAPE [OpenID.PAPE] max_auth_age request parameter.) When max_age is used, the ID Token returned MUST include an …
```
=> feat(oxauth): allow authentication for max_age=0 #1714

Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java, Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java, Server/src/test/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImplTest.java, Server/src/test/resources/testng.xml
Allow end session with expired id_token_hint:
1. Verify the signature on the JWT if present, also checking that it was signed by one of oxAuth's signing keys.
2. As per the spec:
* Use the sid claim in the it token hint to look up the session in the 0xAuth session store.
* If a session is found, check that the aud claim in the token matches one of the client_ids belonging to the session.
If `sid` of id_token_hint does not match request will be rejected. 
New configuration properties:
- `allowEndSessionWithUnmatchedSid` with default value `false`. If `true`, `sid` check will be skipped.
- `rejectEndSessionIfIdTokenExpired` with default value `false`. If `true` and `id_token` is not found in db, request will be rejected.
https://github.com/GluuFederation/oxAuth/issues/1721
=> feat(oxauth): allow end session with expired id_token_hint (by checking signature and sid) #1721

Server/src/main/java/org/gluu/oxauth/model/authorize/JwtAuthorizationRequest.java
Fix NPE
```
java.lang.NullPointerException: null
at org.gluu.oxauth.model.authorize.JwtAuthorizationRequest.createJwtRequest(JwtAuthorizationRequest.java:466) ~[classes/:?]
at org.gluu.oxauth.bcauthorize.ws.rs.BackchannelAuthorizeRestWebServiceImpl.requestBackchannelAuthorizationPost(BackchannelAuthorizeRestWebServiceImpl.java:167) ~[classes/:?]
at org.gluu.oxauth.bcauthorize.ws.rs.BackchannelAuthorizeRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestBackchannelAuthorizationPost(Unknown Source) ~[classes/:?]
at jdk.internal.reflect.GeneratedMethodAccessor660.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
```
https://github.com/GluuFederation/oxAuth/issues/1723
=> fix(oxauth): fix NPE in JwtAuthorizationRequest #1723

Model/src/main/java/org/gluu/oxauth/model/util/Util.java, Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
fix(oxauth): do not unauthenticate session on prompt=login if there was no at least 1 successful redirect to rp
https://github.com/GluuFederation/oxAuth/issues/1712
=> fix(oxauth): do not unauthenticate session on prompt=login if there was no at least 1 successful redirect to rp

Server/src/main/java/org/gluu/oxauth/service/SessionIdService.java
PKCE parameters from first SSO request retains in futher calls #1733
https://github.com/GluuFederation/oxAuth/issues/1733
=> fix(oxauth): PKCE parameters from first SSO request retains in futher calls #1733

Server/integrations/super_gluu/SuperGluuExternalAuthenticator.py, Server/src/main/java/org/gluu/oxauth/service/fido/u2f/DeviceRegistrationService.java
=> fix: one_step related fixes

Model/src/main/java/org/gluu/oxauth/model/jwt/JwtClaimSet.java, Model/src/test/java/org/gluu/oxauth/model/jwt/JwtClaimsTest.java, Server/src/main/java/org/gluu/oxauth/introspection/ws/rs/IntrospectionWebService.java
fix(oxauth): duplicate iss and aud on introspection as jwt #1748
=> fix(oxauth): duplicate iss and aud on introspection as jwt #1748

Server/src/main/java/org/gluu/oxauth/model/common/AuthorizationGrant.java
fix(oxauth): allow propagate WebApplicationException out of "Update Token" script #1760
=> fix(oxauth): allow propagate WebApplicationException out of "Update Token" script #1760

Model/src/main/java/org/gluu/oxauth/model/common/CallerType.java, Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java, Server/conf/oxauth-config.json, Server/src/main/java/org/gluu/oxauth/model/token/IdTokenFactory.java, Server/src/main/java/org/gluu/oxauth/service/ScopeService.java, Server/src/main/java/org/gluu/oxauth/service/date/DateFormatterService.java, Server/src/main/java/org/gluu/oxauth/userinfo/ws/rs/UserInfoRestWebServiceImpl.java, Server/src/test/java/org/gluu/oxauth/service/DateFormatterServiceTest.java
A new date formatting configuration has been added.
These new default settings start disabled, for backward compatibility.
#1789
=> Feature: Birthdate formatting added, respecting backward compatibility

Server/src/main/java/org/gluu/oxauth/model/authorize/AuthorizeParamsValidator.java
It was compared to `Janssen Project` and the method for validating the `nonce` was not the same as `oxAuth`.
This code fragment was copied into `oxAuth`.
#1795
=> Fix: nonce validation

Server/src/main/java/org/gluu/oxauth/model/registration/RegisterParamsValidator.java, Server/src/test/java/org/gluu/oxauth/model/registration/RegisterParamsValidatorTest.java
Added validation when `redirect_uri` does not exist in `sector_identifier_uri`.
#1799
=> Fix: Sector identifier is bad

Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java, Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java
fix(oxauth): dynamic registration - assign to client only scopes which are explicitly in request #1815
=> fix(oxauth): dynamic registration - assign to client only scopes which are explicitly in request #1815

pom.xml
chore(oxauth): jettison 1.5.2 -> 1.5.4
=> chore(oxauth): jettison 1.5.2 -> 1.5.4

Server/src/main/java/org/gluu/oxauth/model/token/IdTokenFactory.java
fix(oxauth): unnecessary "session not found" error messages during refresh token flow #1824
=> fix(oxauth): unnecessary "session not found" error messages during refresh token flow #1824

Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebService.java, Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java, Server/src/test/java/org/gluu/oxauth/session/ws/rs/EndSessionRestWebServiceImplTest.java
feat(oxauth): added client_id parameter support to /end_session (4.6.0)
https://github.com/GluuFederation/oxAuth/issues/1853
=> feat(oxauth): added client_id parameter support to /end_session (4.6.0)

Model/src/main/java/org/gluu/oxauth/model/configuration/AppConfiguration.java, Server/src/main/java/org/gluu/oxauth/introspection/ws/rs/IntrospectionWebService.java
feat(oxauth): added configuration property to AS which will allow to bypass basic client authentication restriction to query only own tokens (4.6.0)
https://github.com/GluuFederation/oxAuth/issues/1865
=> feat(oxauth): added configuration property to AS which will allow to bypass basic client authentication restriction to query only own tokens (4.6.0)

Server/src/main/java/org/gluu/oxauth/token/ws/rs/TokenRestWebServiceImpl.java, Server/src/main/java/org/gluu/oxauth/util/ServerUtil.java, Server/src/test/java/org/gluu/oxauth/util/ServerUtilTest.java, Server/src/test/resources/testng.xml
fix(oxauth): client secret printed on logs
https://github.com/GluuFederation/oxAuth/issues/1811
=> fix(oxauth): client secret printed on logs

Model/src/main/java/org/gluu/oxauth/model/jwt/JwtType.java, Model/src/test/java/org/gluu/oxauth/model/jwt/JwtTypeTest.java
feat(oxauth): uppercased typ=JWT #1903
Closes #1903
```
If present, it is RECOMMENDED that
its value be "JWT" to indicate that this object is a JWT.  While
media type names are not case sensitive, it is RECOMMENDED that "JWT"
always be spelled using uppercase characters for compatibility with
legacy implementations.  Use of this Header Parameter is OPTIONAL.
```
=> feat(oxauth): uppercased typ=JWT #1903

Server/src/main/resources/oxauth.properties, Server/src/main/webapp/login.xhtml
The "Login" text was not visible in the login button of the login form.
This fixes it.
=> Removed  whitespace from login.xhtml login button value attribute and empty login.login property from oxauth.properties.

Server/src/main/java/org/gluu/oxauth/service/GrantService.java, Server/src/main/java/org/gluu/oxauth/token/ws/rs/TokenRestWebServiceImpl.java
fix(oxauth): corrected race condition during refresh token usage (4.5.5)
https://github.com/GluuFederation/oxAuth/issues/1909
Support: 11874
=> fix(oxauth): corrected race condition during refresh token usage (4.5.5)

Server/src/main/java/org/gluu/oxauth/introspection/ws/rs/IntrospectionWebService.java
Introspection endpoint returns error for valid basic client authentication and invalid token 
closes #1916
=> fix(oxauth): introspection endpoint returns error for valid basic client authentication and invalid token #1916

Server/src/main/java/org/gluu/oxauth/util/ServerUtil.java, Server/src/test/java/org/gluu/oxauth/util/ServerUtilTest.java
fix(oxauth): Plaintext passwords logged from TokenRestWebServiceImpl with DEBUG log level #1910
=> fix(oxauth): Plaintext passwords logged from TokenRestWebServiceImpl with DEBUG log level #1910
